lsi: false
safe: true

source: .

title: OpenMaine
email: hello@openmaine.org
description: OpenMaine's website

baseurl: /OpenMaine_ForkedFromLA
url: https://openmaine.github.io/


collections:
  hack-nights:
  press:
  projects:
    output: true
  sponsors:
  testimonials:

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
